services:

  flask-app:
    build: .
    container_name: flask-api

    environment:
     APP_NAME: "Tholiwe DevOps Portfolio"
     APP_ENV: "Production"

    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-server

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - flask-app

    restart: unless-stopped